---
- hosts: firewalls
  connection: local
  gather_facts: False
  
  roles:
    - role: PaloAltoNetworks.paloaltonetworks
  
  tasks:
    - name: Create NAT SSH rule for 10.0.1.101
      panos_nat_rule:
       provider: 
           username : "{{admin_username}}"
           password : "{{admin_username}}"
           ip_address : "{{mgmt_ip}}"
           api_key : "{{api_key}}"
       rule_name: "{{rule_name}}"
       description: 'An Ansible test rule'
       source_zone: ['any']
       destination_zone: ['any']
       source_ip: ["any"]
       destination_ip: ["10.0.0.100"]
       service: "service-tcp-221"
       snat_type: "dynamic-ip-and-port"
       snat_interface: "ethernet1/2"
       dnat_address: "10.0.1.101"
       dnat_port: "22" 