---
- hosts: firewalls
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: fAdd test rule 1 to the firewall
      panos_security_rule:
          provider: 
           username : "{{admin_username}}"
           password : "{{admin_password}}"
           ip_address : "{{mgmt_ip}}"
           api_key : "{{api_key}}"
          source_zone: ['any']
          destination_zone: ['any']
          source_ip: ["11.1.1.1","22.2.2.2"]
          source_user: ['any']
          category: ['any']
          service: ['service-http']
          hip_profiles: ['any']
          action: "allow"
      with_items:
        - { rule_name: "Prod SSH Inbound", destination_ip: ['4.4.4.4'], application: ['ssh'], tag: ['Prod'], description: 'Rule 1 Description'}
        - { rule_name: "SI Inbound", destination_ip: ['4.4.4.4'], application: ['ssh', 'mysql'], tag: ['Prod'],description:'Rule 2 Description'}	   