---
- hosts: firewalls
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: add a rule to allow HTTP
      panos_security_rule:
        ip_address: "xx.yy.zz.tt"
        username: "network"
        password: "xxxxxx"
        operation: 'add'
        rule_name: "{{ rule_name }}"
        application: "{{ application }}"
        description: "{{ description }}"
        source_zone: ['untrust']
        destination_zone: ['trust']
        action: 'allow'
        commit: "False"
