---
- hosts: firewalls
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: fAdd test rule 1 to the firewall
      panos_security_rule:
          provider: 
           username : "{{admin_username}}"
           password : "{{admin_password}}"
           ip_address : "{{mgmt_ip}}"
           api_key : "{{api_key}}"
          rule_name: "{{rule_name}}"
          description: 'An Ansible test rule'
          source_zone: ['any']
          destination_zone: ['any']
          source_ip: ["11.1.1.1","22.2.2.2"]
          source_user: ['any']
          destination_ip: ['any'] 
          category: ['any']
          application: ['any']
          service: ['service-http']
          hip_profiles: ['any']
          action: "{{action_verb}}"
          commit: 'True'