---
- hosts: firewalls
  connection: local
  gather_facts: False
  
  tasks:
    - name: Create NAT SSH rule for 10.0.1.101
      panos_nat_rule:
      provider: '{{ provider }}'
      rule_name: "Web SSH"
      source_zone: ["external"]
      destination_zone: "external"
      source_ip: ["any"]
      destination_ip: ["10.0.0.100"]
      service: "service-tcp-221"
      snat_type: "dynamic-ip-and-port"
      snat_interface: "ethernet1/2"
      dnat_address: "10.0.1.101"
      dnat_port: "22" 