---
- hosts: firewalls
  connection: local
  gather_facts: False
  
  roles:
    - role: PaloAltoNetworks.paloaltonetworks
  
  tasks:
  
    - name: Create tag object 'Prod'
      panos_tag_object:
        provider: 
           username : "{{admin_username}}"
           password : "{{admin_username}}"
           ip_address : "{{mgmt_ip}}"
           api_key : "{{api_key}}"
        name: 'Prod'
        color: 'red'
        comments: 'Prod Environment'  
    
    - name: Create Service service-tcp-221
      panos_service_object:
        provider: 
           username : "{{admin_username}}"
           password : "{{admin_username}}"
           ip_address : "{{mgmt_ip}}"
           api_key : "{{api_key}}"
        name: 'service-tcp-221'
        destination_port: '22'
        description: 'service-tcp-221'
        tag: ['Prod']